### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by thedanheller** [generative-light/p5.scribble.js#1]
I'm a beginner on Processing and P5 and would love to see some examples of how to use this lib. Many thanks.

**Comment by jawu** [comment]
Hey Danilo,
I will add some examples to this repo during the next week.
Best wishes, jawu.

**Comment by thedanheller** [comment]
Hey, I hadn't realised I can just transpose from the normal p5 methods :) but it'd still be great to see these examples. thanks!

**Comment by jawu** [comment]
Hey Danilo,
I added an examples folder to this repo and added a bar graph example where you can see scribbleLine, scribbleRect and scribbleFilling in action.
I hope this is a little bit helpful. In the future there will be a few more.
jawu

**Comment by thedanheller** [comment]
thanks a lot!
