### ISSUE TITLE
Node.js

### ISSUE THREAD

**Issue by pwichmann** [generative-light/p5.scribble.js#2]
This looks incredible!

Is there any way to run this on node.js?
What would I need to set up to make it happen?

**Comment by jawu** [comment]
Hi!
What exactly is your goal?
You can serve a website from node.js which contains p5.js and p5.scribble.js to draw sketchy things like you can do it on any other webseite too.

Or are you looking to render such images on the server to serve them as static images?

**Comment by pwichmann** [comment]
Thanks for your reply.
I wanted to do both - draw things but also render them into *.pngs.

The general problem with JS libraries for *.svg processing that I ran into (without being an expert myself yet) is that JS requires the browser environment to parse / manipulate the DOM which is not given in node.js.
So you have two options: use a browser like PhantomJS or you use JSDOM.
There were other problems I encountered with other libraries, too, that were written with JS and a browser in mind - instead of a browser-less node.js environment.

Any ideas what - if anything - I would need to take care of to make p5 work with node?

**Comment by jawu** [comment]
Sorry for the late response.
I think the only way is to use phantom.js at the moment.
I was able to run p5.js with phantom.js headless but not the p5.scribble.js lib.
Trying to get this working in the next days.

**Comment by jawu** [comment]
Is this still a point of interest for you?

**Comment by pwichmann** [comment]
Hi, yes!
This is still of interest to me! Thank you for asking!

**Comment by jawu** [comment]
Hi!
I've changed the lib to work with a reference to the p5 instance. This was necessary to get this work with phantomJS. In the example directory you will find a phantomjs fiolder with the bar graph example in it.
Also you can use this as a skeleton project for further work with phantomJS and p5.js.

Hope this helps you! Let me know if you need further help with this.

**Comment by pwichmann** [comment]
Thank you! I will look into this over the next days!
