### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by BenjamintGibbs** [generative-light/p5.scribble.js#3]
For some reason I can't get it to work? There are no errors in console?

<!doctype html>
<html lang="en">
  <head>
    <meta charset ="UTF-8">
    <title> Scribbler </title>
    <script src="p5.js"></script>
    <script src="p5.sound.js"></script>
    <script src="p5.scribble.js"></script>
  </head>
  <body>
  <script>

  function setup() {
    createCanvas(600,600);
    background();
    var scribble = new Scribble();
  }

  function draw() {
    fill(255,0,0);
    scribble.scribbleRect(300,300,80,80);

  }

  </script>
  </body>
</html>

**Comment by jawu** [comment]
You are defining the var scribble inside the setup function. In the draw function scribble is not known so.
You should get a ReferenceError in the console.
Here is a fixed version:

`<!DOCTYPE html>
<html>
<head>
<title> Scribbler </title>
<script src="p5.js"></script>
<script src="p5.sound.js"></script>
<script src="p5.scribble.js"></script>
<script>
var scribble = new Scribble();
function setup() {
createCanvas(600,600);
background(255);
}

function draw() {
fill(255,0,0);
scribble.scribbleRect(300,300,80,80);
}
</script>
</head>
<body></body>
</html>`

Please build correct html markup.
Hope this help you start.

**Comment by BenjamintGibbs** [comment]
Yeah I tried that, get nothing but black canvas:

**Comment by jawu** [comment]
you have to change the color with stroke( r, g, b). At this moment you are drawing a black rect on black background.
