### ISSUE TITLE
typos?

### ISSUE THREAD

**Issue by nkint** [generative-light/p5.scribble.js#6]
Hi!
I'm trying to port your library in my project where I'm using es6 and standard js linter style.

I've found something that can be considered typos:

line 40:
```cthis.sketch.urveVertex( this.getOffset( -offset, offset )+cx+rx*Math.cos( radialOffset+Math.PI*2+overlap*0.5 ),```

with `cthis` you mean `this`?

line 366:
```  if (((otherSegment.getPy1()-yi)*(yi-otherSegment.getPy2()) < -0.00001) || ((y1-yi)*(yi-y2) < -000001)) {```
with `-000001` you mean `-0.000001`?

**Comment by jawu** [comment]
Thank you for opening this issue.
The mistake in line 40 happened when I updated the lib the last time. 
The missing dot in line 366 comes from the original processing lib handy written in java but is now corrected. I will open an issue there.
